version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000  # Add this line
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - techblog_network
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - techblog_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - techblog_network

  nginx:
      build:
        context: .
        dockerfile: docker/nginx/Dockerfile
      volumes:
        - static_volume:/app/static
        - media_volume:/app/media
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - ./docker/nginx/certs:/etc/nginx/certs
      ports:
        - "8080:80"  # Changed from 80:80
        - "8443:443" # Changed from 443:443
      depends_on:
        - web
      networks:
        - techblog_network

networks:
  techblog_network:

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: