# Generated by Django 4.2.7 on 2024-12-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequest',
            options={'verbose_name': 'API Request', 'verbose_name_plural': 'API Requests'},
        ),
    ]
